apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: najmuj-mieszkanie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: najmuj-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          readinessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /up
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
