apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: najmuj-mieszkanie
type: Opaque
stringData:
  APP_KEY: "base64:6CS/4TxmRQvSl1ixTU3ArDiWsKi6yJGWsL7gLyQdE1o="
  DB_PASSWORD: "NajmujPass123!"
  DB_ROOT_PASSWORD: "RootPass123!"
