<?php

namespace Database\Seeders;

use App\Enums\FurnishingType;
use App\Enums\PropertyStatus;
use App\Enums\PropertyType;
use App\Enums\RentalPeriod;
use App\Models\Property;
use App\Models\PropertyImage;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $owner = User::where('email', 'owner@example.com')->first();

        $properties = [

            // ═══════════════════════════════════════════════
            // MIESZKANIA
            // ═══════════════════════════════════════════════

            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Przestronne 3-pokojowe na Mokotowie',
                'short_description' => 'Jasne mieszkanie blisko metra Wilanowska. Garaż w cenie.',
                'description' => 'Piękne umeblowane mieszkanie 68 m² na 3. piętrze nowoczesnego budynku. Salon z aneksem, 2 sypialnie, łazienka i WC. Winda, garaż podziemny, balkon.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Mokotów',
                'street' => 'ul. Puławska 120', 'postal_code' => '02-624',
                'area' => 68.00, 'rooms_count' => 3, 'bathrooms_count' => 1,
                'floor' => 3, 'total_floors' => 8,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2018,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 3800.00, 'admin_fee' => 450.00, 'deposit' => 7600.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(14)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(5),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Kawalerka w centrum Krakowa - Stare Miasto',
                'short_description' => 'Klimatyczna kawalerka w kamienicy, 200 m od Rynku.',
                'description' => 'Urokliwa kawalerka 32 m² w zabytkowej kamienicy. Wysoki pułap, parkiet, duże okna. Aneks kuchenny, łazienka z prysznicem. Po generalnym remoncie.',
                'voivodeship' => 'małopolskie', 'city' => 'Kraków', 'district' => 'Stare Miasto',
                'street' => 'ul. Grodzka 15', 'postal_code' => '31-006',
                'area' => 32.00, 'rooms_count' => 1, 'bathrooms_count' => 1,
                'floor' => 2, 'total_floors' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1920,
                'parking' => false, 'elevator' => false, 'balcony' => false,
                'price' => 2400.00, 'admin_fee' => 300.00, 'deposit' => 4800.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(7)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(3),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Nowoczesne 2-pokojowe Wrocław Śródmieście',
                'short_description' => 'Nowe budownictwo 2021, klimatyzacja, ogrzewanie podłogowe.',
                'description' => 'Mieszkanie 50 m² w nowym budynku. Salon z aneksem, sypialnia, łazienka, duży balkon. Klimatyzacja, ogrzewanie podłogowe. Recepcja, wózkowania, monitoring.',
                'voivodeship' => 'dolnośląskie', 'city' => 'Wrocław', 'district' => 'Śródmieście',
                'street' => 'ul. Świdnicka 44', 'postal_code' => '50-028',
                'area' => 50.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 5, 'total_floors' => 10,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2021,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 3200.00, 'admin_fee' => 380.00, 'deposit' => 6400.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(10),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Rodzinne 4-pokojowe Gdańsk Wrzeszcz z ogródkiem',
                'short_description' => 'Parter z ogródkiem 40 m², blisko szkoły i parku.',
                'description' => 'Przestronne mieszkanie 85 m² na parterze z ogródkiem. 3 sypialnie, salon, 2 łazienki. Częściowo umeblowane. Spokojne osiedle, dużo zieleni.',
                'voivodeship' => 'pomorskie', 'city' => 'Gdańsk', 'district' => 'Wrzeszcz',
                'street' => 'ul. Grunwaldzka 112', 'postal_code' => '80-244',
                'area' => 85.00, 'rooms_count' => 4, 'bathrooms_count' => 2,
                'floor' => 0, 'total_floors' => 3,
                'furnishing' => FurnishingType::PartiallyFurnished->value, 'year_built' => 2005,
                'parking' => true, 'elevator' => false, 'balcony' => false,
                'price' => 4200.00, 'admin_fee' => 500.00, 'deposit' => 8400.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(30)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => false,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(2),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Klimatyczne 2-pokojowe Poznań Jeżyce',
                'short_description' => 'Kamienica w modnej dzielnicy, blisko Starego Browaru.',
                'description' => 'Mieszkanie 45 m² w remontowanej kamienicy. Oryginalne parkiety, wysokie sufity. Salon z aneksem, sypialnia, łazienka z wanną.',
                'voivodeship' => 'wielkopolskie', 'city' => 'Poznań', 'district' => 'Jeżyce',
                'street' => 'ul. Dąbrowskiego 22', 'postal_code' => '60-407',
                'area' => 45.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 1, 'total_floors' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1935,
                'parking' => false, 'elevator' => false, 'balcony' => false,
                'price' => 2600.00, 'admin_fee' => 320.00, 'deposit' => 5200.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(7)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(8),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Loftowe studio z tarasem 20 m² - Łódź Piotrkowska',
                'short_description' => 'Poprzemysłowy loft po rewitalizacji, ogromny taras.',
                'description' => 'Studio 38 m² w poprzemysłowym budynku. Otwarta przestrzeń, aneks kuchenny, łazienka z prysznicem, taras 20 m². Klimat industrialny.',
                'voivodeship' => 'łódzkie', 'city' => 'Łódź', 'district' => 'Śródmieście',
                'street' => 'ul. Piotrkowska 200', 'postal_code' => '90-361',
                'area' => 38.00, 'rooms_count' => 1, 'bathrooms_count' => 1,
                'floor' => 4, 'total_floors' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2019,
                'parking' => false, 'elevator' => true, 'balcony' => true,
                'price' => 2100.00, 'admin_fee' => 250.00, 'deposit' => 4200.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(1),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => '3-pokojowe na Ursynowie blisko SGGW',
                'short_description' => 'Spokojne osiedle, metro Kabaty w 10 min, parking.',
                'description' => 'Mieszkanie 62 m² na osiedlu Kabaty. Salon, 2 sypialnie, łazienka, balkon z widokiem na park. Blisko metra Kabaty i SGGW.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Ursynów',
                'street' => 'ul. Przy Bażantarni 5', 'postal_code' => '02-860',
                'area' => 62.00, 'rooms_count' => 3, 'bathrooms_count' => 1,
                'floor' => 7, 'total_floors' => 11,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2000,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 3400.00, 'admin_fee' => 420.00, 'deposit' => 6800.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(21)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(12),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Nowe mieszkanie 2-pokojowe Gdynia Śródmieście',
                'short_description' => 'Widok na morze, nowe budownictwo, parking podziemny.',
                'description' => 'Mieszkanie 48 m² z pięknym widokiem na morze. Salon z aneksem, sypialnia, łazienka. Nowy budynek 2022, wysoki standard.',
                'voivodeship' => 'pomorskie', 'city' => 'Gdynia', 'district' => 'Śródmieście',
                'street' => 'ul. Świętojańska 30', 'postal_code' => '81-372',
                'area' => 48.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 8, 'total_floors' => 12,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2022,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 3500.00, 'admin_fee' => 400.00, 'deposit' => 7000.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(10)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(4),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Komfortowe 2-pokojowe Katowice centrum',
                'short_description' => 'Wysoki standard, tuż przy Spodku, dobra komunikacja.',
                'description' => 'Mieszkanie 52 m² w centrum Katowic. Salon, sypialnia, łazienka z wanną i prysznicem, balkon. Pełne wyposażenie, zmywarka, pralka.',
                'voivodeship' => 'śląskie', 'city' => 'Katowice', 'district' => 'Centrum',
                'street' => 'ul. Mariacka 10', 'postal_code' => '40-014',
                'area' => 52.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 4, 'total_floors' => 9,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2015,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 2800.00, 'admin_fee' => 350.00, 'deposit' => 5600.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(5)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(6),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Penthouse 4-pokojowy Warszawa Wilanów',
                'short_description' => 'Luksusowy apartament z tarasem 50 m², widok na Wisłę.',
                'description' => 'Ekskluzywny apartament 110 m² na ostatnim piętrze. 3 sypialnie, 2 łazienki, salon z jadalnią, kuchnia wyposażona w sprzęt premium. Ogromny taras 50 m² z widokiem na Wisłę i Centrum Warszawy.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Wilanów',
                'street' => 'ul. Przyczółkowa 40', 'postal_code' => '02-968',
                'area' => 110.00, 'rooms_count' => 4, 'bathrooms_count' => 2,
                'floor' => 12, 'total_floors' => 12,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2020,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 8500.00, 'admin_fee' => 800.00, 'deposit' => 17000.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(30)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => false,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(15),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Tanie 2-pokojowe Bydgoszcz Fordon',
                'short_description' => 'Tanie, spokojne, blisko parku i przedszkola.',
                'description' => 'Mieszkanie 44 m² na osiedlu Fordon. Salon, sypialnia, kuchnia, łazienka. Okna na południe, dużo światła. Blisko centrum handlowego i parku.',
                'voivodeship' => 'kujawsko-pomorskie', 'city' => 'Bydgoszcz', 'district' => 'Fordon',
                'street' => 'ul. Akademicka 15', 'postal_code' => '85-796',
                'area' => 44.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 2, 'total_floors' => 5,
                'furnishing' => FurnishingType::PartiallyFurnished->value, 'year_built' => 1990,
                'parking' => true, 'elevator' => false, 'balcony' => true,
                'price' => 1600.00, 'admin_fee' => 280.00, 'deposit' => 3200.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(20),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Mieszkanie 3-pokojowe Lublin Sławin',
                'short_description' => 'Spokojne osiedle, blisko KUL i UMCS.',
                'description' => 'Mieszkanie 58 m² na spokojnym osiedlu Sławin. Salon, 2 sypialnie, kuchnia, łazienka, loggia. Dobre połączenie z centrum i uczelniami.',
                'voivodeship' => 'lubelskie', 'city' => 'Lublin', 'district' => 'Sławin',
                'street' => 'ul. Poniatowskiego 22', 'postal_code' => '20-055',
                'area' => 58.00, 'rooms_count' => 3, 'bathrooms_count' => 1,
                'floor' => 4, 'total_floors' => 7,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2010,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 2200.00, 'admin_fee' => 300.00, 'deposit' => 4400.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(14)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(11),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Kawalerka Szczecin Śródmieście - idealna dla singla',
                'short_description' => 'Mała ale funkcjonalna, po remoncie, metro tramwajowe.',
                'description' => 'Kawalerka 28 m² po generalnym remoncie w 2023. Aneks kuchenny z pełnym wyposażeniem, łazienka z prysznicem. Blisko Urzędu Miasta i placu Lotników.',
                'voivodeship' => 'zachodniopomorskie', 'city' => 'Szczecin', 'district' => 'Śródmieście',
                'street' => 'ul. Monte Cassino 18', 'postal_code' => '70-466',
                'area' => 28.00, 'rooms_count' => 1, 'bathrooms_count' => 1,
                'floor' => 3, 'total_floors' => 6,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1970,
                'parking' => false, 'elevator' => false, 'balcony' => false,
                'price' => 1800.00, 'admin_fee' => 220.00, 'deposit' => 3600.00,
                'rental_period' => RentalPeriod::Minimum3Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 3,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(18),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => '2-pokojowe Rzeszów Nowe Miasto - nowy blok',
                'short_description' => 'Świeżo oddany budynek, pierwsze piętro, parking gratis.',
                'description' => 'Mieszkanie 46 m² w nowym budynku oddanym w 2023. Salon z aneksem, sypialnia, łazienka, balkon. Stan deweloperski wykończony przez właściciela na wysokim poziomie.',
                'voivodeship' => 'podkarpackie', 'city' => 'Rzeszów', 'district' => 'Nowe Miasto',
                'street' => 'ul. Rejtana 44', 'postal_code' => '35-326',
                'area' => 46.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 1, 'total_floors' => 6,
                'furnishing' => FurnishingType::PartiallyFurnished->value, 'year_built' => 2023,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 2300.00, 'admin_fee' => 290.00, 'deposit' => 4600.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(7)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(9),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Mieszkanie 3-pokojowe Białystok Centrum',
                'short_description' => 'Centralna lokalizacja, blisko galerii Alfa i Biała.',
                'description' => 'Mieszkanie 55 m² w centrum Białegostoku. Salon, 2 sypialnie, kuchnia, łazienka. Budynek po termomodernizacji, niskie rachunki za ogrzewanie.',
                'voivodeship' => 'podlaskie', 'city' => 'Białystok', 'district' => 'Centrum',
                'street' => 'ul. Lipowa 40', 'postal_code' => '15-426',
                'area' => 55.00, 'rooms_count' => 3, 'bathrooms_count' => 1,
                'floor' => 5, 'total_floors' => 8,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1985,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 2000.00, 'admin_fee' => 270.00, 'deposit' => 4000.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(14)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(7),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Nowe 2-pokojowe Toruń Bydgoskie Przedmieście',
                'short_description' => 'Spokojna ulica, nowy budynek, blisko Starego Miasta.',
                'description' => 'Mieszkanie 43 m² w nowym budynku. Salon z aneksem kuchennym, sypialnia, łazienka, balkon. 15 minut pieszo do Starówki.',
                'voivodeship' => 'kujawsko-pomorskie', 'city' => 'Toruń', 'district' => 'Bydgoskie Przedmieście',
                'street' => 'ul. Bydgoska 55', 'postal_code' => '87-100',
                'area' => 43.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 2, 'total_floors' => 5,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2020,
                'parking' => true, 'elevator' => false, 'balcony' => true,
                'price' => 1900.00, 'admin_fee' => 250.00, 'deposit' => 3800.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(10)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(13),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => '2-pokojowe Kraków Krowodrza po remoncie',
                'short_description' => 'Kamienica 1930, nowa instalacja, dobra komunikacja.',
                'description' => 'Mieszkanie 40 m² po kompleksowym remoncie. Salon, sypialnia, nowa kuchnia, nowa łazienka z prysznicem. Wysokie sufity, parkiet.',
                'voivodeship' => 'małopolskie', 'city' => 'Kraków', 'district' => 'Krowodrza',
                'street' => 'ul. Karmelicka 55', 'postal_code' => '31-131',
                'area' => 40.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 1, 'total_floors' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1930,
                'parking' => false, 'elevator' => false, 'balcony' => false,
                'price' => 2700.00, 'admin_fee' => 330.00, 'deposit' => 5400.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(5)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(16),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Duże 4-pokojowe Wrocław Psie Pole',
                'short_description' => 'Przestronne mieszkanie dla rodziny, cichy rejon.',
                'description' => 'Mieszkanie 78 m² na spokojnym osiedlu. 3 sypialnie, salon, 2 łazienki, balkon. Piwnica w cenie. Dobre połączenie tramwajowe z centrum.',
                'voivodeship' => 'dolnośląskie', 'city' => 'Wrocław', 'district' => 'Psie Pole',
                'street' => 'ul. Składowa 8', 'postal_code' => '51-609',
                'area' => 78.00, 'rooms_count' => 4, 'bathrooms_count' => 2,
                'floor' => 3, 'total_floors' => 6,
                'furnishing' => FurnishingType::PartiallyFurnished->value, 'year_built' => 2012,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 3600.00, 'admin_fee' => 450.00, 'deposit' => 7200.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(21)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => false,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(22),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Kawalerka Gdańsk Oliwa blisko PG',
                'short_description' => 'Mała, przytulna, przy parku oliwskim.',
                'description' => 'Kawalerka 30 m² w pobliżu parku Oliwskiego. Aneks kuchenny, łazienka. Bardzo spokojna okolica, blisko Politechniki Gdańskiej.',
                'voivodeship' => 'pomorskie', 'city' => 'Gdańsk', 'district' => 'Oliwa',
                'street' => 'ul. Polanki 15', 'postal_code' => '80-308',
                'area' => 30.00, 'rooms_count' => 1, 'bathrooms_count' => 1,
                'floor' => 2, 'total_floors' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1965,
                'parking' => false, 'elevator' => false, 'balcony' => false,
                'price' => 1950.00, 'admin_fee' => 240.00, 'deposit' => 3900.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(3)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(25),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => '3-pokojowe Poznań Grunwald z garażem',
                'short_description' => 'Popularna dzielnica, blisko AWF i UM Poznań.',
                'description' => 'Mieszkanie 60 m² na osiedlu Grunwald. Salon, 2 sypialnie, kuchnia, łazienka. Garaż w cenie najmu. Nowa kuchnia i łazienka.',
                'voivodeship' => 'wielkopolskie', 'city' => 'Poznań', 'district' => 'Grunwald',
                'street' => 'ul. Grunwaldzka 80', 'postal_code' => '60-311',
                'area' => 60.00, 'rooms_count' => 3, 'bathrooms_count' => 1,
                'floor' => 4, 'total_floors' => 8,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1998,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 2900.00, 'admin_fee' => 360.00, 'deposit' => 5800.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(14)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(14),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Mieszkanie 2-pokojowe Warszawa Praga Południe',
                'short_description' => 'Nowy blok, metro Dworzec Wileński w pobliżu.',
                'description' => 'Mieszkanie 47 m² w nowym budynku na Pradze. Salon z aneksem, sypialnia, łazienka, balkon. Bardzo dobra komunikacja z centrum.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Praga-Południe',
                'street' => 'ul. Grochowska 200', 'postal_code' => '04-357',
                'area' => 47.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 6, 'total_floors' => 9,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2017,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 3100.00, 'admin_fee' => 370.00, 'deposit' => 6200.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(7)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(17),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Mieszkanie nieumeblowane 3-pokojowe Kraków Nowa Huta',
                'short_description' => 'Tanie, duże, do urządzenia po swojemu.',
                'description' => 'Duże mieszkanie 65 m² bez mebli - do urządzenia samemu. Salon, 2 sypialnie, kuchnia, łazienka, loggia. Idealne dla rodziny.',
                'voivodeship' => 'małopolskie', 'city' => 'Kraków', 'district' => 'Nowa Huta',
                'street' => 'os. Centrum B 5', 'postal_code' => '31-927',
                'area' => 65.00, 'rooms_count' => 3, 'bathrooms_count' => 1,
                'floor' => 3, 'total_floors' => 9,
                'furnishing' => FurnishingType::Unfurnished->value, 'year_built' => 1975,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 1900.00, 'admin_fee' => 310.00, 'deposit' => 3800.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(30),
            ],

            // ═══════════════════════════════════════════════
            // POKOJE
            // ═══════════════════════════════════════════════

            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój dla studentki Warszawa Ochota - blisko SGH',
                'short_description' => 'Jasny pokój 14 m² w kobiecym mieszkaniu.',
                'description' => 'Pokój 14 m² w 3-osobowym kobiecym mieszkaniu. Pełna kuchnia, pralka, internet. Blisko kampusu SGH i Politechniki.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Ochota',
                'street' => 'ul. Filtrowa 68', 'postal_code' => '02-032',
                'room_area' => 14.00, 'apartment_area' => 72.00, 'roommates_count' => 2, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 2, 'total_floors' => 6,
                'price' => 1400.00, 'deposit' => 1400.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(5)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true, 'only_women' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(4),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Duży pokój 18 m² Kraków centrum z balkonem',
                'short_description' => 'Spokojne mieszkanie, 2 pracujących współlokatorów.',
                'description' => 'Pokój 18 m² z balkonem w 3-pokojowym mieszkaniu w kamienicy. Współlokatorzy to pracujące osoby 25-30 lat. Szybki internet, Netflix wspólny.',
                'voivodeship' => 'małopolskie', 'city' => 'Kraków', 'district' => 'Krowodrza',
                'street' => 'ul. Karmelicka 30', 'postal_code' => '31-131',
                'room_area' => 18.00, 'apartment_area' => 80.00, 'roommates_count' => 2, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 3, 'total_floors' => 4,
                'price' => 1350.00, 'deposit' => 1350.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(10)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(6),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój w nowym bloku Wrocław Krzyki',
                'short_description' => 'Nowe budownictwo, tylko dwie osoby, czysto i spokojnie.',
                'description' => 'Pokój 12 m² w nowym 2-pokojowym mieszkaniu. Jedna osoba - pracujący mężczyzna. Wspólna łazienka, kuchnia wyposażona. Osiedle strzeżone.',
                'voivodeship' => 'dolnośląskie', 'city' => 'Wrocław', 'district' => 'Krzyki',
                'street' => 'ul. Powstańców Śląskich 200', 'postal_code' => '53-315',
                'room_area' => 12.00, 'apartment_area' => 48.00, 'roommates_count' => 1, 'total_rooms_count' => 2,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 4, 'total_floors' => 7,
                'parking' => true, 'elevator' => true,
                'price' => 1100.00, 'deposit' => 1100.00,
                'rental_period' => RentalPeriod::Minimum3Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 3,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(9),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Tani pokój studencki Gdańsk Wrzeszcz blisko PG',
                'short_description' => 'Media w cenie, 5 min pieszo do Politechniki.',
                'description' => 'Pokój 11 m² w 4-osobowym mieszkaniu studenckim. Internet, pralka, zmywarka. Media wliczone do 200 zł/mies.',
                'voivodeship' => 'pomorskie', 'city' => 'Gdańsk', 'district' => 'Wrzeszcz',
                'street' => 'ul. Siedlecka 8', 'postal_code' => '80-299',
                'room_area' => 11.00, 'apartment_area' => 75.00, 'roommates_count' => 3, 'total_rooms_count' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 1, 'total_floors' => 4,
                'price' => 900.00, 'deposit' => 900.00, 'additional_costs' => 'Media wliczone do 200 zł/mies.',
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(20)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(7),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 15 m² Warszawa Wola - blisko metra',
                'short_description' => 'Nowy budynek, metro Rondo Daszyńskiego 5 min.',
                'description' => 'Pokój 15 m² w nowoczesnym 3-pokojowym mieszkaniu. Współlokatorzy to pracujące osoby. Netflix, internet, pralka, zmywarka wspólne.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Wola',
                'street' => 'ul. Kasprzaka 25', 'postal_code' => '01-211',
                'room_area' => 15.00, 'apartment_area' => 65.00, 'roommates_count' => 2, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 5, 'total_floors' => 12,
                'elevator' => true,
                'price' => 1600.00, 'deposit' => 1600.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(7)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(3),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój dla studenta Kraków AGH Krowodrza',
                'short_description' => 'Idealne dla studenta AGH - 7 min pieszo.',
                'description' => 'Pokój 13 m² w 4-osobowym mieszkaniu studenckim. Budynek po remoncie, nowa łazienka i kuchnia. Internet światłowodowy.',
                'voivodeship' => 'małopolskie', 'city' => 'Kraków', 'district' => 'Krowodrza',
                'street' => 'ul. Lea 30', 'postal_code' => '30-052',
                'room_area' => 13.00, 'apartment_area' => 70.00, 'roommates_count' => 3, 'total_rooms_count' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 2, 'total_floors' => 4,
                'price' => 1100.00, 'deposit' => 1100.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(14)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(5),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Jasny pokój 16 m² Poznań Stary Browar',
                'short_description' => 'Prestiżowa lokalizacja, cicha ulica, wysoki standard.',
                'description' => 'Pokój 16 m² w 3-pokojowym mieszkaniu w centrum Poznania. Współlokatorki to młode pracujące kobiety. Wysoki standard wykończenia.',
                'voivodeship' => 'wielkopolskie', 'city' => 'Poznań', 'district' => 'Centrum',
                'street' => 'ul. Półwiejska 10', 'postal_code' => '61-888',
                'room_area' => 16.00, 'apartment_area' => 75.00, 'roommates_count' => 2, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 3, 'total_floors' => 5,
                'price' => 1300.00, 'deposit' => 1300.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(5)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true, 'only_women' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(10),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój z własną łazienką Warszawa Wilanów',
                'short_description' => 'Luksusowe mieszkanie, prywatna łazienka do pokoju.',
                'description' => 'Pokój 20 m² z własną łazienką w luksusowym 4-pokojowym mieszkaniu. Współlokatorzy to pracownicy korporacji. Klub fitness w budynku.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Wilanów',
                'street' => 'ul. Klimczaka 12', 'postal_code' => '02-797',
                'room_area' => 20.00, 'apartment_area' => 120.00, 'roommates_count' => 2, 'total_rooms_count' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 8, 'total_floors' => 15,
                'elevator' => true, 'parking' => true,
                'price' => 2200.00, 'deposit' => 2200.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(30)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => false,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(2),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 10 m² Łódź Śródmieście - dla studenta',
                'short_description' => 'Najtaniej w centrum, blisko PŁ i UŁ.',
                'description' => 'Mały ale funkcjonalny pokój 10 m² w 5-osobowym mieszkaniu studenckim. Niska cena, wszelkie udogodnienia. Blisko uczelni.',
                'voivodeship' => 'łódzkie', 'city' => 'Łódź', 'district' => 'Śródmieście',
                'street' => 'ul. Wschodnia 22', 'postal_code' => '90-272',
                'room_area' => 10.00, 'apartment_area' => 80.00, 'roommates_count' => 4, 'total_rooms_count' => 5,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 1, 'total_floors' => 3,
                'price' => 750.00, 'deposit' => 750.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(8),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 17 m² Wrocław Stare Miasto z widokiem',
                'short_description' => 'Zabytkowa kamienica, widok na kościół, 3 min do Rynku.',
                'description' => 'Pokój 17 m² w pięknej kamienicy przy Rynku. Mieszkanie zajmuje dwoje młodych pracujących. Pełne wyposażenie, szybki internet.',
                'voivodeship' => 'dolnośląskie', 'city' => 'Wrocław', 'district' => 'Stare Miasto',
                'street' => 'ul. Świdnicka 10', 'postal_code' => '50-067',
                'room_area' => 17.00, 'apartment_area' => 85.00, 'roommates_count' => 1, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 3, 'total_floors' => 5,
                'price' => 1500.00, 'deposit' => 1500.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(7)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(11),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 12 m² Gdańsk Zaspa blisko Sopotu',
                'short_description' => 'Spokojna okolica, 20 min tramwajem do Sopotu.',
                'description' => 'Pokój 12 m² w 3-pokojowym mieszkaniu. Dwóch spokojnych współlokatorów. Blisko plaży gdańskiej i szybkiej kolei miejskiej SKM.',
                'voivodeship' => 'pomorskie', 'city' => 'Gdańsk', 'district' => 'Zaspa',
                'street' => 'ul. Rzeczypospolitej 15', 'postal_code' => '80-369',
                'room_area' => 12.00, 'apartment_area' => 55.00, 'roommates_count' => 2, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 5, 'total_floors' => 11,
                'elevator' => true,
                'price' => 1050.00, 'deposit' => 1050.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(3)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(19),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój w domu jednorodzinnym Poznań Jeżyce',
                'short_description' => 'Dom z ogródkiem, cisza i spokój, niedrogo.',
                'description' => 'Pokój 14 m² w domu jednorodzinnym z ogrodem. Tylko jedna osoba w domu - starsza pani. Kuchnia, łazienka do dyspozycji. Idealne dla spokojnej osoby.',
                'voivodeship' => 'wielkopolskie', 'city' => 'Poznań', 'district' => 'Jeżyce',
                'street' => 'ul. Szamarzewskiego 30', 'postal_code' => '60-567',
                'room_area' => 14.00, 'apartment_area' => 130.00, 'roommates_count' => 0, 'total_rooms_count' => 5,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 0, 'total_floors' => 2,
                'parking' => true,
                'price' => 1000.00, 'deposit' => 1000.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(14)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(23),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 13 m² Katowice Centrum - pracownicy mile widziani',
                'short_description' => 'Czyste mieszkanie, 2 współlokatorów, metro tramwajowe.',
                'description' => 'Pokój 13 m² w centrum Katowic. Mieszkanie zajmuje dwóch pracujących mężczyzn. Kuchnia, łazienka, internet, pralka.',
                'voivodeship' => 'śląskie', 'city' => 'Katowice', 'district' => 'Centrum',
                'street' => 'ul. Kościuszki 30', 'postal_code' => '40-048',
                'room_area' => 13.00, 'apartment_area' => 58.00, 'roommates_count' => 2, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 2, 'total_floors' => 5,
                'price' => 950.00, 'deposit' => 950.00,
                'rental_period' => RentalPeriod::Minimum3Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 3,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => false,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(15),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 20 m² Kraków Podgórze - duży i jasny',
                'short_description' => 'Największy pokój w mieszkaniu, własna umywalka.',
                'description' => 'Duży, jasny pokój 20 m² z własną umywalką w 3-pokojowym mieszkaniu. Jedna współlokatorka. Blisko Kazimierza i Podgórza. Modna okolica.',
                'voivodeship' => 'małopolskie', 'city' => 'Kraków', 'district' => 'Podgórze',
                'street' => 'ul. Limanowskiego 25', 'postal_code' => '30-551',
                'room_area' => 20.00, 'apartment_area' => 70.00, 'roommates_count' => 1, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 1, 'total_floors' => 4,
                'price' => 1500.00, 'deposit' => 1500.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(7)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(26),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 11 m² Warszawa Żoliborz niedrogo',
                'short_description' => 'Spokojna zielona dzielnica, metro Stare Bielany blisko.',
                'description' => 'Pokój 11 m² w 4-pokojowym mieszkaniu na Żoliborzu. Trzech spokojnych współlokatorów. Czysto i spokojnie. Blisko parku Żeromskiego.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Żoliborz',
                'street' => 'ul. Mickiewicza 18', 'postal_code' => '01-517',
                'room_area' => 11.00, 'apartment_area' => 78.00, 'roommates_count' => 3, 'total_rooms_count' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 4, 'total_floors' => 6,
                'price' => 1200.00, 'deposit' => 1200.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(10)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(28),
            ],
            // --- dodatkowe mieszkania ---
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Mieszkanie 2-pokojowe Kraków Podgórze - Kazimierz',
                'short_description' => 'Modna okolica Kazimierza, blisko restauracji i galerii.',
                'description' => 'Mieszkanie 42 m² w klimatycznej kamienicy na Podgórzu. Salon, sypialnia, łazienka. Wysokie sufity, oryginalne kafle. 5 min do Kazimierza.',
                'voivodeship' => 'małopolskie', 'city' => 'Kraków', 'district' => 'Podgórze',
                'street' => 'ul. Kalwaryjska 18', 'postal_code' => '30-504',
                'area' => 42.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 2, 'total_floors' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1910,
                'parking' => false, 'elevator' => false, 'balcony' => false,
                'price' => 2500.00, 'admin_fee' => 310.00, 'deposit' => 5000.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(5)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(4),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Słoneczne 2-pokojowe Warszawa Bemowo',
                'short_description' => 'Spokojne osiedle, dobre przedszkola, park w pobliżu.',
                'description' => 'Mieszkanie 49 m² na osiedlu przy parku. Salon, sypialnia, łazienka, balkon na południe. Ciepłe i jasne przez cały rok.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Bemowo',
                'street' => 'ul. Lazurowa 14', 'postal_code' => '01-315',
                'area' => 49.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 4, 'total_floors' => 10,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2008,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 3000.00, 'admin_fee' => 370.00, 'deposit' => 6000.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(10)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(6),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Nowe 3-pokojowe Wrocław Fabryczna',
                'short_description' => 'Nowy budynek 2022, wysoki standard, dwie łazienki.',
                'description' => 'Mieszkanie 72 m² w nowym budynku. Salon z jadalnią, 2 sypialnie, 2 łazienki, balkon 8 m². Pełne wyposażenie, klimatyzacja w salonie.',
                'voivodeship' => 'dolnośląskie', 'city' => 'Wrocław', 'district' => 'Fabryczna',
                'street' => 'ul. Lotnicza 22', 'postal_code' => '54-155',
                'area' => 72.00, 'rooms_count' => 3, 'bathrooms_count' => 2,
                'floor' => 4, 'total_floors' => 8,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2022,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 4100.00, 'admin_fee' => 480.00, 'deposit' => 8200.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(7)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(3),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Kawalerka Warszawa Śródmieście - idealna pod wynajem',
                'short_description' => 'Centrum Warszawy, metro Centrum 3 min pieszo.',
                'description' => 'Funkcjonalna kawalerka 26 m² w samym centrum Warszawy. Aneks kuchenny, łazienka. Wszystko w odległości pieszej.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Śródmieście',
                'street' => 'ul. Marszałkowska 50', 'postal_code' => '00-624',
                'area' => 26.00, 'rooms_count' => 1, 'bathrooms_count' => 1,
                'floor' => 6, 'total_floors' => 10,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1975,
                'parking' => false, 'elevator' => true, 'balcony' => false,
                'price' => 2700.00, 'admin_fee' => 330.00, 'deposit' => 5400.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(1),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => '2-pokojowe Gdańsk Letnica blisko stadionu',
                'short_description' => 'Nowa inwestycja, dobra komunikacja, parking.',
                'description' => 'Mieszkanie 44 m² przy Parku Reagana. Salon, sypialnia, łazienka, balkon. Nowy budynek, wysoki standard, monitoring.',
                'voivodeship' => 'pomorskie', 'city' => 'Gdańsk', 'district' => 'Letnica',
                'street' => 'ul. Starogardska 5', 'postal_code' => '80-556',
                'area' => 44.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 3, 'total_floors' => 7,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 2019,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 2800.00, 'admin_fee' => 340.00, 'deposit' => 5600.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(14)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(5),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Mieszkanie 3-pokojowe Sopot przy plaży',
                'short_description' => 'Prestiżowa lokalizacja, 500 m od morza.',
                'description' => 'Wyjątkowe mieszkanie 65 m² w Sopocie. Salon, 2 sypialnie, łazienka. Blisko mola i plaży. Idealne na długoterminowy wynajem.',
                'voivodeship' => 'pomorskie', 'city' => 'Sopot', 'district' => 'Centrum',
                'street' => 'ul. Bohaterów Monte Cassino 30', 'postal_code' => '81-759',
                'area' => 65.00, 'rooms_count' => 3, 'bathrooms_count' => 1,
                'floor' => 2, 'total_floors' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'year_built' => 1960,
                'parking' => true, 'elevator' => false, 'balcony' => true,
                'price' => 5500.00, 'admin_fee' => 600.00, 'deposit' => 11000.00,
                'rental_period' => RentalPeriod::Minimum12Months->value,
                'available_from' => now()->addDays(30)->toDateString(), 'min_rental_months' => 12,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => false,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(7),
            ],
            [
                'property_type' => PropertyType::Apartment->value,
                'title' => 'Mieszkanie 2-pokojowe Częstochowa Centrum',
                'short_description' => 'Tanie centrum, blisko Jasnej Góry, parking gratis.',
                'description' => 'Mieszkanie 48 m² w centrum Częstochowy. Salon, sypialnia, kuchnia, łazienka. Blisko Alei NMP i Jasnej Góry.',
                'voivodeship' => 'śląskie', 'city' => 'Częstochowa', 'district' => 'Centrum',
                'street' => 'ul. Kopernika 12', 'postal_code' => '42-200',
                'area' => 48.00, 'rooms_count' => 2, 'bathrooms_count' => 1,
                'floor' => 3, 'total_floors' => 7,
                'furnishing' => FurnishingType::PartiallyFurnished->value, 'year_built' => 1985,
                'parking' => true, 'elevator' => true, 'balcony' => true,
                'price' => 1500.00, 'admin_fee' => 220.00, 'deposit' => 3000.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(20),
            ],
            // --- dodatkowe pokoje ---
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 16 m² Wrocław Nadodrze klimatyczny',
                'short_description' => 'Artystyczna dzielnica, kamienica po remoncie, 3 osoby.',
                'description' => 'Pokój 16 m² w wyremontowanej kamienicy w modnej dzielnicy Nadodrze. Trzech kreatywnych współlokatorów. Piękne wnętrze, szybki internet.',
                'voivodeship' => 'dolnośląskie', 'city' => 'Wrocław', 'district' => 'Nadodrze',
                'street' => 'ul. Roosevelta 8', 'postal_code' => '50-236',
                'room_area' => 16.00, 'apartment_area' => 90.00, 'roommates_count' => 2, 'total_rooms_count' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 2, 'total_floors' => 4,
                'price' => 1250.00, 'deposit' => 1250.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(5)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => true, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(9),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 14 m² Warszawa Praga Północ',
                'short_description' => 'Modna Praga, tętniące życiem kulturalne.',
                'description' => 'Pokój 14 m² w 3-pokojowym mieszkaniu na Pradze. Dwóch pracujących współlokatorów. Blisko Stadionu, Centrum Praskie Koneser.',
                'voivodeship' => 'mazowieckie', 'city' => 'Warszawa', 'district' => 'Praga-Północ',
                'street' => 'ul. Ząbkowska 20', 'postal_code' => '03-736',
                'room_area' => 14.00, 'apartment_area' => 62.00, 'roommates_count' => 2, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 1, 'total_floors' => 4,
                'price' => 1350.00, 'deposit' => 1350.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(7)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(12),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 15 m² Kraków Nowa Huta tani wynajem',
                'short_description' => 'Najtaniej w Krakowie, linia tramwajowa do centrum.',
                'description' => 'Pokój 15 m² w 4-pokojowym mieszkaniu. Trzech studentów. Pralka, zmywarka, szybki internet. Tramwaj do centrum AGH 20 min.',
                'voivodeship' => 'małopolskie', 'city' => 'Kraków', 'district' => 'Nowa Huta',
                'street' => 'os. Na Skarpie 10', 'postal_code' => '31-913',
                'room_area' => 15.00, 'apartment_area' => 72.00, 'roommates_count' => 3, 'total_rooms_count' => 4,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 6, 'total_floors' => 9,
                'elevator' => true,
                'price' => 850.00, 'deposit' => 850.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(3)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(14),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 18 m² Gdańsk Wrzeszcz z balkonem',
                'short_description' => 'Własny balkon, dwie spokojne osoby w mieszkaniu.',
                'description' => 'Duży pokój 18 m² z prywatnym balkonem w 3-pokojowym mieszkaniu. Dwie pracujące osoby. Kuchnia i łazienka nowe. Blisko SKM Gdańsk Wrzeszcz.',
                'voivodeship' => 'pomorskie', 'city' => 'Gdańsk', 'district' => 'Wrzeszcz',
                'street' => 'ul. Jaśkowa Dolina 12', 'postal_code' => '80-252',
                'room_area' => 18.00, 'apartment_area' => 68.00, 'roommates_count' => 2, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 2, 'total_floors' => 5,
                'balcony' => true,
                'price' => 1200.00, 'deposit' => 1200.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(10)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(16),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 13 m² Poznań Wilda spokojna okolica',
                'short_description' => 'Zielona dzielnica, tramwaj do centrum 10 min.',
                'description' => 'Pokój 13 m² w 3-pokojowym mieszkaniu na Wildzie. Jedna współlokatorka - pracująca kobieta. Czysto, spokojnie, dobra atmosfera.',
                'voivodeship' => 'wielkopolskie', 'city' => 'Poznań', 'district' => 'Wilda',
                'street' => 'ul. Górna Wilda 25', 'postal_code' => '61-563',
                'room_area' => 13.00, 'apartment_area' => 55.00, 'roommates_count' => 1, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 1, 'total_floors' => 4,
                'price' => 1050.00, 'deposit' => 1050.00,
                'rental_period' => RentalPeriod::Minimum6Months->value,
                'available_from' => now()->addDays(5)->toDateString(), 'min_rental_months' => 6,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true, 'only_women' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(21),
            ],
            [
                'property_type' => PropertyType::Room->value,
                'title' => 'Pokój 12 m² Łódź Bałuty niedrogo',
                'short_description' => 'Budżetowa opcja, czysto, tramwaj do centrum.',
                'description' => 'Pokój 12 m² w 3-pokojowym mieszkaniu na Bałutach. Dwóch spokojnych współlokatorów. Pełna kuchnia, łazienka, pralka, internet.',
                'voivodeship' => 'łódzkie', 'city' => 'Łódź', 'district' => 'Bałuty',
                'street' => 'ul. Zgierska 55', 'postal_code' => '91-002',
                'room_area' => 12.00, 'apartment_area' => 58.00, 'roommates_count' => 2, 'total_rooms_count' => 3,
                'furnishing' => FurnishingType::Furnished->value, 'floor' => 2, 'total_floors' => 4,
                'price' => 800.00, 'deposit' => 800.00,
                'rental_period' => RentalPeriod::Minimum3Months->value,
                'available_from' => now()->toDateString(), 'min_rental_months' => 3,
                'pets_allowed' => false, 'smoking_allowed' => false, 'students_allowed' => true,
                'status' => PropertyStatus::Published->value, 'published_at' => now()->subDays(18),
            ],
        ];

        $baseUrl   = config('app.url');
        $roomImgs  = [
            "{$baseUrl}/placeholders/Pokoj_1.jpg",
            "{$baseUrl}/placeholders/Pokoj_2.jpg",
            "{$baseUrl}/placeholders/Pokoj_3.jpg",
        ];
        $aptImgs   = [
            "{$baseUrl}/placeholders/Mieszkanie_1.jpg",
            "{$baseUrl}/placeholders/Mieszkanie_2.jpg",
            "{$baseUrl}/placeholders/Mieszkanie_3.jpg",
        ];

        foreach ($properties as $data) {
            $data['user_id'] = $owner->id;
            $data['slug']    = $this->uniqueSlug($data['title']);

            $property = Property::create($data);

            // Przypisz 3 losowe zdjecia (przetasowane)
            $pool = $data['property_type'] === PropertyType::Room->value ? $roomImgs : $aptImgs;
            $shuffled = collect($pool)->shuffle()->values();

            $mainId = null;
            foreach ($shuffled as $order => $url) {
                $img = PropertyImage::create([
                    'property_id' => $property->id,
                    'path'        => $url,
                    'filename'    => basename($url),
                    'order'       => $order,
                    'is_main'     => $order === 0,
                ]);
                if ($order === 0) {
                    $mainId = $img->id;
                }
            }

            $property->update(['main_image_id' => $mainId]);
        }
    }

    private function uniqueSlug(string $title): string
    {
        $base = Str::slug($title);
        $slug = $base;
        $i    = 1;
        while (Property::where('slug', $slug)->exists()) {
            $slug = "{$base}-{$i}";
            $i++;
        }
        return $slug;
    }
}
